### ISSUE TITLE
you cannot claim more lands -1 

### ISSUE THREAD

**Issue by testadler** [SpatiumPrinceps/LandLord#14]
New player geht an error on claiming land 

The Store is disabled in my config
and i migrate the old lands vom v1

all i working fine but all players excluded the op and admins cant buy lands

/ll claim & /ll buy want work but the get this -1 error message

**Comment by SpatiumPrinceps** [comment]
This is not an issue, but a feature xD You need to give the default player a max permission of lands they should be able to claim. E.g. landlord.limits.10 allows a player to claim 10 lands. Atleast if they have bought enough claims from /ll shop :)

I will see if I can get around this in one of the future patches

**Comment by SpatiumPrinceps** [comment]
I added default permission for landlord.limit.10. If you dont want to use this system, just give landlord.limit.override to all players
