### ISSUE TITLE
suggest >> gui

### ISSUE THREAD

**Issue by mat41997** [SpatiumPrinceps/LandLord#15]
add a gui
![9q8x3p](https://user-images.githubusercontent.com/5884000/28875609-6be7231a-7796-11e7-9eec-ab55b2301954.jpg)

**Comment by SpatiumPrinceps** [comment]
What do you mean? These already is one in ll manage

**Comment by mat41997** [comment]
add a image on your site
https://www.spigotmc.org/resources/beta-landlord-2.44398/

i want see this

**Comment by SpatiumPrinceps** [comment]
http://imgur.com/a/ADtLk
Added a bunch of pictures to the description :)

**Comment by mat41997** [comment]
ok. thx
