### ISSUE TITLE
Break and place anywhere

### ISSUE THREAD

**Issue by BackSlashM** [SpatiumPrinceps/LandLord#41]
In version 132 users and break and place blocks anywhere regardless of weather they are allowed by the land permissions or not. 

I'm not sure what starts this weird behavior (it seems to be random) but most of the time it starts when a user breaks a block holding shift.

Here is a video of the problem: https://www.youtube.com/watch?v=887HDS-swEA

**Comment by SpatiumPrinceps** [comment]
This is indeed very weird. 
Have no idea what causes this, but will investigate it immediately!

**Comment by BackSlashM** [comment]
The account that claimed the land is op, but the player that was breaking blocks wasn't

**Comment by SpatiumPrinceps** [comment]
Can you send me a copy of your config? 
What Spigot Version (build number) are you using? 
What version of worldguard?

**Comment by BackSlashM** [comment]
Spigot: 1.12.2 - R0.1-SNAPSHOT
WorldGuard - 6.2.1

[config.txt](https://github.com/SpatiumPrinceps/LandLord/files/1532302/config.txt)

**Comment by BackSlashM** [comment]
It was my mistake all along, need to make sure that if the server has a region covering the whole map with build permissions in WG, you need to give it a lower priority than the ones LL creates

**Comment by SpatiumPrinceps** [comment]
Alright, sounds plausible :) 
If you want to protect the free lands you can also use that new threshold function. 
If anything else is on your mind, don't hesitate to contact me.
