### ISSUE TITLE
Cant claim more than 10..

### ISSUE THREAD

**Issue by AconTM** [SpatiumPrinceps/LandLord#46]
Hi, i have give my users the perms:
landlord.player.*
landlord.limit.100

but they cant claim any chunk... there always a message wich says " you cant claim more lands then 10!" 

pls help :/

Version: newest
Server: 1.11.2

**Comment by SpatiumPrinceps** [comment]
Hello,

it totally depends on your config. You may just write a 100 in the limit list :)

**Comment by AconTM** [comment]
Shop:
# set this to false, if you want to use the traditional permission based system
  enable: true
  extras:
    - PAPER:10:5000.0
    - PAPER:20:9000.0
    - PAPER:30:13500.0
    - PAPER:50:45000.0

# These are hard caps. If a player has the permission "landlord.limit.10" he will be able to buy up to 20 lands, but cant buy more claims than that.
limits:
  - 10
  - 20
  - 30
  - 100


But it still not work

**Comment by SpatiumPrinceps** [comment]
Yeayea, if you only want exactly one limit(100) delete the other entries in the limits list. A player needs to have the permission for all minor limits
