### ISSUE TITLE
UUID Fetcher throws ugly error

### ISSUE THREAD

**Issue by SpatiumPrinceps** [SpatiumPrinceps/LandLord#50]
from time to time (maybe to many connections) or timeouts the uuid server doesnt respond and a nasty error is thrown. Catch it and make it pretty :3

**Comment by VictoryAndGlory** [comment]
It also doesnt allow us to manage friends in our claims. When I write "/land manage" and click to friends, I see bunch of Heads and NuLL descriptions. And friends cannot break any block or use any containers etc. (OPs can but players cant.)

**Comment by SpatiumPrinceps** [comment]
@VictoryAndGlory
This seems to be related to #47

**Comment by VictoryAndGlory** [comment]
Our players want to play as a team. This is not low priority for us. But this plugin is totally what we were looking for and we do not want to change the plugin. So we can wait for a fix. May I learn will you work to fix it or ignore it?

**Comment by SpatiumPrinceps** [comment]
@VictoryAndGlory
I would never ignore an issue, thats why its on the list :) 
So you are on cracked, right? 

I would really love to work out something, but right now I just have to get the exams done >.< 
Someone else said, that he might work on a fix, so maybe you are lucky... 
If you know something feel free to submit a pull request. 

Good night :)

**Comment by VictoryAndGlory** [comment]
We are going to wait for a new release then. Thank you. Have a good night.
