### ISSUE TITLE
Error addfriend

### ISSUE THREAD

**Issue by IronDirt** [SpatiumPrinceps/LandLord#56]
[BETA] Landlord 2 b144

/land addfriend [player]   --->  Aggiunge il player al claim ma non lo fa costruire. (non funziona con i player che hanno un numero nel nickname)

Se faccio:
/rg addmembers [claim name] [player]   --->  Funziona e lo fa costruire.

Fix this Bug?

**Comment by SpatiumPrinceps** [comment]
English pls

**Comment by IronDirt** [comment]
"Google Translate" :D

/land addfriend [player] ---> Adds the player to the claim but does not build it. (does not work with players that have a number in the nickname)

If I do:
/rg addmembers [claim name] [player] ---> It works and makes it build.

Fix this Bug?

**Comment by SpatiumPrinceps** [comment]
Are you on cracked?

**Comment by IronDirt** [comment]
server offline mode

**Comment by SpatiumPrinceps** [comment]
Check out the latest build. It doesnt fix the actual problem, but I'm so fed up fixing stuff for people, who are not willing to spend a few bucks on an awesome game.
