### ISSUE TITLE
Armour stand, vehicles and water entry

### ISSUE THREAD

**Issue by 112madgamer** [SpatiumPrinceps/LandLord#9]
Would you be able to add deny of Armour stand breaking and minecart / boat breaking. Also deny water/lava entry into claims?

**Comment by SpatiumPrinceps** [comment]
Armorstands cannot be broken or interacted with. 
Will add the rest :)

**Comment by SpatiumPrinceps** [comment]
Should be fixed now. I haven't tested it heavily, but it should work fine :+1:

**Comment by 112madgamer** [comment]
Awesome could you please kick off a ci build.

**Comment by SpatiumPrinceps** [comment]
Done, just trying to figure out how to do the autobuild on commit ^^

**Comment by 112madgamer** [comment]
I know how to do that just to much to explain in a issue lol check this out though

https://www.fourkitchens.com/blog/article/trigger-jenkins-builds-pushing-github/

If you need anymore help with Jenkins or any CI PM on discord 
112
#5336

**Comment by SpatiumPrinceps** [comment]
Got it to work, thank you :)
